### ISSUE TITLE
AGP7.0报错，考虑支持下吗

### ISSUE THREAD

**Issue by loyal888** [bytedance/CodeLocator#10]
错误信息：
AGPBI: {"kind":"error","text":"java.lang.IllegalArgumentException","sources":[{"file":"/Users/Desktop/My-Application/app/build/intermediates/transforms/lancet/debug/136/com/loyal888/myapplication/adapter/MyHolder$_lancet.class"}],"tool":"D8"}

版本：
    classpath 'com.bytedance.tools.lancet:lancet-plugin-asm6:1.0.2'
    debugImplementation "com.bytedance.tools.codelocator:codelocator-core:1.0.0"
    debugImplementation "com.bytedance.tools.codelocator:codelocator-lancet-xml:1.0.0"
    debugImplementation "com.bytedance.tools.codelocator:codelocator-lancet-activity:1.0.0"
    debugImplementation "com.bytedance.tools.codelocator:codelocator-lancet-view:1.0.0"
    debugImplementation "com.bytedance.tools.codelocator:codelocator-lancet-toast:1.0.0"
    debugImplementation "com.bytedance.tools.codelocator:codelocator-lancet-dialog:1.0.0"
    debugImplementation "com.bytedance.tools.codelocator:codelocator-lancet-popup:1.0.0"
    compileOnly 'me.ele:lancet-base:1.0.6'

**Comment by liujianAndroid** [comment]
CodeLocatorApp升级了AGP7 没啥问题 可以clone试下  应该是项目里的某些写法有问题。 可以加我微信排查下

**Comment by loyal888** [comment]
ByteX和Codelocator 不兼容引起，二选一 for now
