### ISSUE TITLE
开启手机代理怎么在手机上关闭？

### ISSUE THREAD

**Issue by Jadyli** [bytedance/CodeLocator#11]
好几次在电脑上开启了手机代理，然后一出门发现连不上网了。。。。。
这个跟自己在 wifi 里设置的不一样，没法在手机上关。。。

**Comment by liujianAndroid** [comment]
> 
adb shell settings put global http_proxy :0 
adb shell settings delete global http_proxy
adb shell settings delete global global_http_proxy_host
adb shell settings delete global global_http_proxy_port

**Comment by Jadyli** [comment]
解决方案：出门前忘记关代理的话，出门了可以直接关闭开发者调试模式解决！
