### ISSUE TITLE
Type com.bytedance.tools.codelocator.utils.CodeLocatorUtils$Transform is defined multiple times: 

### ISSUE THREAD

**Issue by makeloveandroid** [bytedance/CodeLocator#12]
Type com.bytedance.tools.codelocator.utils.CodeLocatorUtils$Transform is defined multiple times: /Users/wengege/Desktop/project/CodeLocator/CodeLocatorApp/app/build/intermediates/mixed_scope_dex_archive/debug/out/1f36d78ddc6a93310a4477926a88cdafb759110006bde10cfc003e05844cb00a_1.jar:classes.dex, /Users/wengege/Desktop/project/CodeLocator/CodeLocatorApp/app/build/intermediates/mixed_scope_dex_archive/debug/out/52239907ab4e2b8d58f10838fd58b5fc22a6f1bfd7ff2ac3f146f2c4b949bdfb_1.jar:classes.dex

app依赖方式改成

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.3.2'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.recyclerview:recyclerview:1.2.0'

//    implementation 'com.bytedance.tools.codelocator:codelocator-core:1.0.0'
//    debugImplementation "com.bytedance.tools.codelocator:codelocator-lancet-xml:1.0.0"
//    debugImplementation "com.bytedance.tools.codelocator:codelocator-lancet-activity:1.0.0"
//    debugImplementation "com.bytedance.tools.codelocator:codelocator-lancet-view:1.0.0"
//    debugImplementation "com.bytedance.tools.codelocator:codelocator-lancet-toast:1.0.0"
//    debugImplementation "com.bytedance.tools.codelocator:codelocator-lancet-dialog:1.0.0"
//    debugImplementation "com.bytedance.tools.codelocator:codelocator-lancet-popup:1.0.0"
    implementation project(path: ':CodeLocatorLancetXml')
    implementation project(path: ':CodeLocatorCore')
    implementation project(path: ':CodeLocatorLancetActivity')
    implementation project(path: ':CodeLocatorLancetToast')
    implementation project(path: ':CodeLocatorLancetPopup')
    implementation project(path: ':CodeLocatorLancetView')
    implementation project(path: ':CodeLocatorLancetDialog')

    compileOnly 'me.ele:lancet-base:1.0.6'
}

编译 App 有遇到这个问题吗？？我发现 CodeLocatorUtils 在2个jar中

**Comment by LiuJian2** [comment]
> Type com.bytedance.tools.codelocator.utils.CodeLocatorUtils$Transform is defined multiple times: /Users/wengege/Desktop/project/CodeLocator/CodeLocatorApp/app/build/intermediates/mixed_scope_dex_archive/debug/out/1f36d78ddc6a93310a4477926a88cdafb759110006bde10cfc003e05844cb00a_1.jar:classes.dex, /Users/wengege/Desktop/project/CodeLocator/CodeLocatorApp/app/build/intermediates/mixed_scope_dex_archive/debug/out/52239907ab4e2b8d58f10838fd58b5fc22a6f1bfd7ff2ac3f146f2c4b949bdfb_1.jar:classes.dex
> 
> app依赖方式改成
> 
> dependencies { implementation fileTree(dir: "libs", include: ["*.jar"]) implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version" implementation 'androidx.core:core-ktx:1.3.2' implementation 'androidx.appcompat:appcompat:1.2.0' implementation 'androidx.recyclerview:recyclerview:1.2.0'
> 
> // implementation 'com.bytedance.tools.codelocator:codelocator-core:1.0.0' // debugImplementation "com.bytedance.tools.codelocator:codelocator-lancet-xml:1.0.0" // debugImplementation "com.bytedance.tools.codelocator:codelocator-lancet-activity:1.0.0" // debugImplementation "com.bytedance.tools.codelocator:codelocator-lancet-view:1.0.0" // debugImplementation "com.bytedance.tools.codelocator:codelocator-lancet-toast:1.0.0" // debugImplementation "com.bytedance.tools.codelocator:codelocator-lancet-dialog:1.0.0" // debugImplementation "com.bytedance.tools.codelocator:codelocator-lancet-popup:1.0.0" implementation project(path: ':CodeLocatorLancetXml') implementation project(path: ':CodeLocatorCore') implementation project(path: ':CodeLocatorLancetActivity') implementation project(path: ':CodeLocatorLancetToast') implementation project(path: ':CodeLocatorLancetPopup') implementation project(path: ':CodeLocatorLancetView') implementation project(path: ':CodeLocatorLancetDialog')
> 
> ```
> compileOnly 'me.ele:lancet-base:1.0.6'
> ```
> 
> }
> 
> 编译 App 有遇到这个问题吗？？我发现 CodeLocatorUtils 在2个jar中

每个 project里面的 codelocator-core依赖也要改成project依赖
