### ISSUE TITLE
当前SDK版本暂不支持抓取Release包, 请检查当前是否使用Release包

### ISSUE THREAD

**Issue by ZouYongpeng** [bytedance/CodeLocator#14]
本地新建一个项目，build.gradle配置sdk为30，build的apk也是debug版本的，
但抓取时提示“当前SDK版本暂不支持抓取Release包, 请检查当前是否使用Release包”
请问我需要把SDK版本设为多少呢？或者如何使用Debug包

build.gradle文件代码如下：

plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.3"

    defaultConfig {
        applicationId "com.example.codelocatordemo"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {

    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.2.0'
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'com.google.android.material:material:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'

    //Code Locator
    implementation "com.bytedance.tools.codelocator:codelocator-core:1.0.0"
    debugImplementation "com.bytedance.tools.codelocator:codelocator-lancet-xml:1.0.0"
    debugImplementation "com.bytedance.tools.codelocator:codelocator-lancet-activity:1.0.0"
    debugImplementation "com.bytedance.tools.codelocator:codelocator-lancet-view:1.0.0"
    debugImplementation "com.bytedance.tools.codelocator:codelocator-lancet-toast:1.0.0"
    debugImplementation "com.bytedance.tools.codelocator:codelocator-lancet-dialog:1.0.0"
    debugImplementation "com.bytedance.tools.codelocator:codelocator-lancet-popup:1.0.0"
}

**Comment by liujianAndroid** [comment]
> 本地新建一个项目，build.gradle配置sdk为30，build的apk也是debug版本的， 但抓取时提示“当前SDK版本暂不支持抓取Release包, 请检查当前是否使用Release包” 请问我需要把SDK版本设为多少呢？或者如何使用Debug包
> 
> build.gradle文件代码如下：
> 
> plugins { id 'com.android.application' id 'kotlin-android' }
> 
> android { compileSdkVersion 30 buildToolsVersion "30.0.3"
> 
> ```
> defaultConfig {
>     applicationId "com.example.codelocatordemo"
>     minSdkVersion 21
>     targetSdkVersion 30
>     versionCode 1
>     versionName "1.0"
> 
>     testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
> }
> 
> buildTypes {
>     release {
>         minifyEnabled false
>         proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
>     }
> }
> compileOptions {
>     sourceCompatibility JavaVersion.VERSION_1_8
>     targetCompatibility JavaVersion.VERSION_1_8
> }
> kotlinOptions {
>     jvmTarget = '1.8'
> }
> ```
> 
> }
> 
> dependencies {
> 
> ```
> implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
> implementation 'androidx.core:core-ktx:1.2.0'
> implementation 'androidx.appcompat:appcompat:1.1.0'
> implementation 'com.google.android.material:material:1.1.0'
> implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
> testImplementation 'junit:junit:4.+'
> androidTestImplementation 'androidx.test.ext:junit:1.1.1'
> androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
> 
> //Code Locator
> implementation "com.bytedance.tools.codelocator:codelocator-core:1.0.0"
> debugImplementation "com.bytedance.tools.codelocator:codelocator-lancet-xml:1.0.0"
> debugImplementation "com.bytedance.tools.codelocator:codelocator-lancet-activity:1.0.0"
> debugImplementation "com.bytedance.tools.codelocator:codelocator-lancet-view:1.0.0"
> debugImplementation "com.bytedance.tools.codelocator:codelocator-lancet-toast:1.0.0"
> debugImplementation "com.bytedance.tools.codelocator:codelocator-lancet-dialog:1.0.0"
> debugImplementation "com.bytedance.tools.codelocator:codelocator-lancet-popup:1.0.0"
> ```
> 
> }

加微信说吧 看依赖没啥问题
