### ISSUE TITLE
点击抓取后 弹框报错 java.lang.NullPointerException

### ISSUE THREAD

**Issue by pengMaster** [bytedance/CodeLocator#17]
1.异常：点击抓取后 弹框报错 java.lang.NullPointerException
2.日志：控制台没有任何报错信息
3.Android studio 版本 2021.1.1 petch 1 
4.其他环境：jdk 11

**Comment by liujianAndroid** [comment]
有集成SDK么

**Comment by pengMaster** [comment]
@liujianAndroid  android sdk 已经集成，未设置CodeLocator的MinSdk

**Comment by pengMaster** [comment]
> @liujianAndroid android sdk 已经集成，未设置CodeLocator的MinSdk

<img width="417" alt="image" src="https://user-images.githubusercontent.com/19420491/172286390-47dc37aa-bf76-4424-9175-af2dc45f2779.png">

**Comment by pengMaster** [comment]
> 有集成SDK么

我知道什么原因导致的了，我集成的依赖是 1.0.0，使用的插件是2.0.0，不匹配了，所以报错，也就是说2.0.0的插件不兼容依赖1.0.0了，需要修复

**Comment by liujianAndroid** [comment]
嗯 2.0.0的插件就是不兼容1.0.0的 插件里已经说明了
