### ISSUE TITLE
windows android studio 内中文显示乱码

### ISSUE THREAD

**Issue by Jadyli** [bytedance/CodeLocator#18]
![image](https://user-images.githubusercontent.com/15962904/175286787-a00e561b-f134-45f5-a3b7-5901f7800658.png)
![image](https://user-images.githubusercontent.com/15962904/175286834-a4145d33-7435-4272-b523-4e8cfcbf95bf.png)

**Comment by liujianAndroid** [comment]
字体问题  Preferences | Appearance & Behavior | Appearance 里面 use custom font 打开 换字体看看

**Comment by Jadyli** [comment]
![image](https://user-images.githubusercontent.com/15962904/175519399-7295825b-45f9-4c1e-b2ca-c99908bc9278.png)
@liujianAndroid 尝试了几个，比如设置到仿宋，微软雅黑，都是乱码。

**Comment by Jadyli** [comment]
我的问题，Appearance  里换字体好了。
