### ISSUE TITLE
打开了显示View深度的选项，但是没发现深度展示在哪呀。

### ISSUE THREAD

**Issue by livelitoday** [bytedance/CodeLocator#29]
打开了显示View深度的选项，但是没发现深度展示在哪呀。

**Comment by livelitoday** [comment]
打开了显示View深度的选项，但是没发现深度展示在哪呀。

**Comment by liujianAndroid** [comment]
> 打开了显示View深度的选项，但是没发现深度展示在哪呀。

View Tree 的展示格式为: [(子View数量) [当前View深度] (可设置显示) 类名 左上顶点坐标 右下顶点坐标 宽度px 高度px 宽度dp 高度dp ]
