### ISSUE TITLE
关于跳转xml失效问题

### ISSUE THREAD

**Issue by OvenCroc** [bytedance/CodeLocator#37]
as 版本:
Android Studio Chipmunk 
Android Studio Flamingo

CodeLocator版本:
2.0.0 2.0.3

在项目集成了codelocator之后, 跳转xml的按钮一直都是灰色的, 找了issue发现说新版本要配置一下 
但是在Application里面也配置了, 跳转xml的按钮依然是灰色, 有没有大佬能帮帮我

**Comment by liujianAndroid** [comment]
咋配置的 发出来看看

**Comment by OvenCroc** [comment]
我就说按照有个issue里面的配置方式

在application的oncreat里调用CodeLocator.config(CodeLocatorConfig.Builder().enableHookInflater(true).build())

我只依赖了两个依赖

   debugImplementation "com.bytedance.tools.codelocator:codelocator-core:2.0.3"
// 依赖lancet-all, 则包含所有lancet能力
   debugImplementation "com.bytedance.tools.codelocator:codelocator-lancet-all:2.0.3"



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年09月08日 10:33 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [bytedance/CodeLocator] 关于跳转xml失效问题 (Issue #37) |

咋配置的 发出来看看

**Comment by ukyo6** [comment]
怎么解决的啊大佬, 我和你配置一样, 也没法跳转xml
在application的oncreat里调用CodeLocator.config(CodeLocatorConfig.Builder().enableHookInflater(true).build())

我只依赖了两个依赖

   debugImplementation "com.bytedance.tools.codelocator:codelocator-core:2.0.3"
// 依赖lancet-all, 则包含所有lancet能力
   debugImplementation "com.bytedance.tools.codelocator:codelocator-lancet-all:2.0.3"
