### ISSUE TITLE
貌似不兼容中文显示耶

### ISSUE THREAD

**Issue by PoisonGZ** [bytedance/CodeLocator#44]
![屏幕截图 2023-11-29 003945](https://github.com/bytedance/CodeLocator/assets/101829490/cc2ad4b5-6eba-44e9-8b97-344d3a63c282)
![图片](https://github.com/bytedance/CodeLocator/assets/101829490/f43082d4-0038-4f16-86fc-bf1b4b0c3ccd)

**Comment by liujianAndroid** [comment]
换个字体试试
