### ISSUE TITLE
Releases和插件商店都没有插件下载

### ISSUE THREAD

**Issue by VamPeng** [bytedance/CodeLocator#51]
<img width="1434" alt="image" src="https://github.com/bytedance/CodeLocator/assets/33115963/44fa4910-1193-42b2-928c-56e62afd0071">
<img width="1332" alt="image" src="https://github.com/bytedance/CodeLocator/assets/33115963/4af9ba72-1943-416f-aa9b-5cd87add7340">
啥情况？下掉了么？

**Comment by liujianAndroid** [comment]
最新版插件已更新 Release中可下载
