### ISSUE TITLE
市场搜不到此插件，且本地安装插件失败

### ISSUE THREAD

**Issue by starlingever** [bytedance/CodeLocator#54]
![image](https://github.com/bytedance/CodeLocator/assets/78263228/8d471a8e-bace-4014-a9ca-388cca018ef1)
code Locator版本为最新版
用的android studio版本：
![image](https://github.com/bytedance/CodeLocator/assets/78263228/777e83dc-e7dd-4120-a7c2-4ddf258d3aee)
什么情况呀

**Comment by starlingever** [comment]
已解决，https://plugins.jetbrains.com/plugin/17447-codelocator/versions/stable在这个网站下载的插件可以。

**Comment by 404-alan** [comment]
@starlingever 老哥，你的抓取视图树的时候，碰到过`SDK is not initialized`这个问题吗？

**Comment by starlingever** [comment]
> @starlingever 老哥，你的抓取视图树的时候，碰到过`SDK is not initialized`这个问题吗？

暂时没有，如果遇到了会通知你
