### ISSUE TITLE
快捷工具弹窗乱码

### ISSUE THREAD

**Issue by AndroidDog** [bytedance/CodeLocator#57]
快捷工具弹窗乱码
![image](https://github.com/bytedance/CodeLocator/assets/8649732/67f05f71-bf61-48b1-999b-37f3154b0a75)

**Comment by liujianAndroid** [comment]
更换下字体

**Comment by DearZack** [comment]
目前尝试了更换成“DialogInput”和“Dialog”这两种字体不会乱码
