### ISSUE TITLE
更新了最新的Android studio 不能使用了

### ISSUE THREAD

**Issue by didixyy** [bytedance/CodeLocator#58]
<img width="1202" alt="image" src="https://github.com/bytedance/CodeLocator/assets/17633836/71876c17-d3f5-4aba-bb26-71e152b108da">
报错是这个，已经升级到最新的2.0.3的版本了
Android Studio是
Android Studio Iguana | 2023.2.1 Patch 1
Build #AI-232.10300.40.2321.11567975, built on March 13, 2024
Runtime version: 17.0.9+0-17.0.9b1087.7-11185874 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.2
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10

**Comment by hanliangel** [comment]
我也报这个错了

**Comment by yingguangchi** [comment]
一样报错,不过单个设备正常,adb devices有多个设备就不行了

**Comment by liujianAndroid** [comment]
2.0.4已修复
