### ISSUE TITLE
Android Studio Koala | 2024.1.1 版本无法使用插件

### ISSUE THREAD

**Issue by owliao** [bytedance/CodeLocator#59]
复现设备：MacOS 14.4.1
复现版本：Android Studio Koala | 2024.1.1 Canary 8
不显示抓取的按钮
![50a8073d8cbc3e831cb3a17f9652500d](https://github.com/bytedance/CodeLocator/assets/70618064/a21b7a1b-2365-4c5b-a388-c4b48881cf2e)

**Comment by liujianAndroid** [comment]
2.0.4已修复
