### ISSUE TITLE
Android Studio JellyFish 2023.3.1 版本，插件导致 git 无法提交代码

### ISSUE THREAD

**Issue by DannyAbc** [bytedance/CodeLocator#66]
使用该版本 as，并结合 codeLocator 使用时，提交代码时偶现异常，导致代码提交失败。as 提示错误：
Commit and push check failed

could not check commit: error in plugin "CodeLocator
![screenshot-20240619-144359](https://github.com/bytedance/CodeLocator/assets/32712691/3e036873-1847-4e0a-bc81-3c5283b01d06)
"

**Comment by liujianAndroid** [comment]
commit的时候 右上角有个remove useless import  不要选中就行

**Comment by HeMing123** [comment]
> commit的时候 右上角有个remove useless import 不要选中就行

方便截图看一下吗？

**Comment by paopao-chen** [comment]
> > commit的时候 右上角有个remove useless import 不要选中就行
> 
> 方便截图看一下吗？

不同版本不同用户习惯可能不同，但都在你的commit设置中(我的2024.1.1在右下角)
<img width="283" alt="image" src="https://github.com/user-attachments/assets/a2e3207b-c8e2-4d3f-9486-dde8fa02aa17">

**Comment by DannyAbc** [comment]
抱歉刚注意到你的邮件，已经按照你们说的方法处理好了发自我的手机-------- 原始邮件 --------发件人： cb-henu ***@***.***>日期： 2024年8月30日周五 14:31收件人： bytedance/CodeLocator ***@***.***>抄送： DannyAbc ***@***.***>, Author ***@***.***>主    题： Re: [bytedance/CodeLocator] Android Studio JellyFish 2023.3.1 版本，插件导致 git 无法提交代码 (Issue #66)


commit的时候 右上角有个remove useless import 不要选中就行

方便截图看一下吗？

不同版本不同用户习惯可能不同，但都在你的commit设置中(我的2024.1.1在右下角)
image.png (view on web)
